version: '3'
services:
    discord-bot:
        build: ./discord_bot
        volumes:
            - ./discord_bot/:/app
        restart: always
        environment:
          - PYTHONUNBUFFERED=1
        env_file:
          - .env
        ports:
            - "8080:8080"